name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    with: {}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }} 
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}    
