name: Test and Lint

on:
  workflow_call:
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  python:
    runs-on: ubuntu-22.04
    steps:
test-pr
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/checkout@v4
 main

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
 test-pr
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Tests
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Run Flake8 Lint

          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Flake8
 main
        run: docker compose run --rm app sh -c "flake8"

  terraform:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Terraform lint
        run: |
          cd Infra/
          docker compose run --rm terraform -chdir=deploy/ init -backend=false
          docker compose run --rm terraform -chdir=setup/ init -backend=false
          docker compose run --rm terraform -chdir=setup/ validate
          docker compose run --rm terraform -chdir=setup/ fmt --check
          docker compose run --rm terraform -chdir=deploy/ validate
          docker compose run --rm terraform -chdir=deploy/ fmt --check
